### ISSUE TITLE
Output is muffled

### ISSUE THREAD

**Issue by playground** [earlephilhower/ESP8266SAM#15]
I tried this on M5Stack Atom Echo Smart Speaker.  The sound is very muffled.  Is there anyway to tune the output?

**Comment by earlephilhower** [comment]
Yeah, that's to be expected.  It was written in the late 70s for <1MHz, 8-bit CPUs with 8KB or less RAM and a 1-bit speaker output, so it's not going to win any awards for speech quality.  It's still amazing what they did, though!
